apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service }}{{ if (ne .Values.release "prod") }}-{{ .Values.release }}{{ end }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service }}
    release: {{ .Values.release }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Values.service }}
  template:
    metadata:
      labels:
        app: {{ .Values.service }}
        release: {{ .Values.release }}
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      {{- if .Values.taintApp }}
      tolerations:
        - key: "app"
          operator: "Equal"
          value: {{ .Values.taintApp }}
          effect: "NoSchedule"
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.poolName }}
      {{ end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - {{ .Values.service }}
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: {{ .Values.service }}
          image: {{ .Values.image }}
          command: {{ .Values.cmd | toJson }}
          envFrom:
            - configMapRef:
                name: {{ .Values.namespace }}-configmap
            - secretRef:
                name: {{ .Values.namespace }}
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
          volumeMounts:
            - mountPath: /var/secrets/google
              name: {{ .Values.namespace }}-iam-secret
          livenessProbe:
            exec:
              command: {{ .Values.healthCheckCmd | toJson }}
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            exec:
              command: {{ .Values.healthCheckCmd | toJson }}
            initialDelaySeconds: 15
            periodSeconds: 30
          ports:
            - containerPort: 8088
              name: http
            - containerPort: 9090
              name: metrics
            - containerPort: 9091
              name: micro-metrics
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: {{ .Values.cpu | quote }}
              memory: {{ .Values.memory | quote }}
      volumes:
        - name: {{ .Values.namespace }}-iam-secret
          secret:
            secretName: {{ .Values.namespace }}-iam-secret

{{ if and .Values.autoscaling (eq .Values.release "prod") }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.service }}-scaling
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.service }}
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{ .Values.maxReplicas }}
  metrics:
  - type: Object
    object:
      describedObject:
        kind: Service
        name: store-autoscale
      metric:
        name: "autoscaling.googleapis.com|gclb-capacity-utilization"
      target:
        averageValue: 80
        type: AverageValue
{{ end }}
