package(default_visibility = ["//visibility:public"])

py_library(
    name = "pubsub",
    srcs = glob([
        "**/*.py",
        "*.py",
    ]),
    deps = ["//frameworks/common/python/utils"],
)
