replicaCount: 2
service: marketdb-api
namespace: marketdb
image: asia-southeast1-docker.pkg.dev/stagvn/marketdb/marketdb-api
release: prod
cpu: 200m
memory: 512Mi
ingress:
  host: m.stag.vn
  hostTlsSecret: stagvn-tls-cert
  prefix: marketdb-api
  publicPrefix: marketdb-public
loglevel: info
serviceMonitor: true
cmd: [
  'python', 'main.zip', '--bind=0.0.0.0:8088', 
    '--log-level=info', 
    '--max-requests=1000',
    '--capture-output', 
    '--timeout=120',
    '--env', 'ENV=production',
    '--env', 'GS_BUCKET_NAME=img.stag.vn',
    '--env', 'MEDIA_URL=https://img.stag.vn',
    '--env', 'GOOGLE_CLOUD_PROJECT=stagvn',
    '--env', 'SERVICE_MONITOR=yes',
    '--env', 'REDIS_STACK_HOST=redis-stack-server.marketdb',
    '--env', 'GOOGLE_OAUTH_CLIENT_ID=101627802077-qpg4ldlabdbar99gf77onrv6m89elite.apps.googleusercontent.com',
]
poolName: services-pool
taintApp: production
hpa:
  autoscaling: true
  minReplicas: 1
  maxReplicas: 2
