package(default_visibility = ["//visibility:public"])

py_library(
    name = "bigquery",
    srcs = glob([
        "**/*.py",
    ]),
    deps = [
        "//frameworks/common/python/utils",
    ],
)
