# Generated by Django 4.1.1 on 2024-09-20 04:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('slug', models.CharField(db_index=True, max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'xpider_category',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('slug', models.CharField(db_index=True, max_length=500)),
                ('type', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('meta_data', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'xpider_entity',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('icb_code', models.CharField(db_index=True, max_length=500)),
                ('level', models.SmallIntegerField(null=True)),
                ('keywords', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'xpider_industry',
            },
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=500)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('language', models.CharField(default='vi', max_length=10)),
                ('extra_data', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'xpider_publisher_pages',
            },
        ),
        migrations.CreateModel(
            name='NERLabel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_uuid', models.UUIDField()),
                ('name', models.CharField(max_length=500)),
                ('label', models.CharField(db_index=True, max_length=50)),
                ('start', models.IntegerField(null=True)),
                ('end', models.IntegerField(null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'xpider_ner_label',
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('slug', models.CharField(db_index=True, max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('published', models.DateTimeField(db_index=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('thumbnail_url', models.TextField(blank=True, null=True)),
                ('publisher_name', models.CharField(blank=True, max_length=100, null=True)),
                ('publisher_website', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(db_index=True, default='cryptocurrency', max_length=50)),
                ('language', models.CharField(db_index=True, default='vi', max_length=50)),
                ('symbols', models.JSONField(default=list)),
                ('topics', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('is_relevant', models.BooleanField(db_index=True, default=True)),
                ('is_recommend', models.BooleanField(db_index=True, default=False)),
                ('relevant_score', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'xpider_post',
            },
        ),
        migrations.CreateModel(
            name='NewsTrending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('doc_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('meta_data', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'xpider_news_trending',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=500)),
                ('slug', models.CharField(db_index=True, max_length=500)),
                ('extra_data', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'xpider_publisher',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic_token', models.CharField(db_index=True, max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('slug', models.CharField(db_index=True, max_length=500)),
                ('type', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('meta_data', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'xpider_topic',
            },
        ),
        migrations.CreateModel(
            name='NewsTopic',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_id', models.CharField(db_index=True, max_length=255)),
                ('topic_token', models.CharField(db_index=True, max_length=500)),
            ],
            options={
                'db_table': 'xpider_news_topic',
                'unique_together': {('doc_id', 'topic_token')},
            },
        ),
        migrations.CreateModel(
            name='NewsIndustry',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_id', models.CharField(db_index=True, max_length=255)),
                ('icb_code', models.CharField(db_index=True, max_length=500)),
                ('is_correct', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'xpider_news_industry',
                'unique_together': {('doc_id', 'icb_code')},
            },
        ),
    ]
