apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.service }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-secret: " {{ .Values.namespace }}/ca-secret"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - pathType: Prefix
            path: /{{ .Values.ingress.prefix }}
            backend:
              service:
                name: {{ .Values.service }}
                port:
                  number: 8088
          - pathType: Prefix
            path: /{{ .Values.ingress.publicPrefix }}
            backend:
              service:
                name: {{ .Values.service }}
                port:
                  number: 8088
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.hostTlsSecret }}
