# Generated by Django 4.1.1 on 2022-11-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpricechart',
            name='movement_1m',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='stockpricechart',
            name='movement_1w',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='stockpricechart',
            name='movement_1y',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='stockpricechart',
            name='movement_3m',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='stockpricechart',
            name='movement_3y',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='stockpricechart',
            name='movement_5y',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='stockpricechart',
            name='movement_6m',
            field=models.JSONField(default=list, null=True),
        ),
    ]
