# Generated by Django 4.1.1 on 2022-11-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stockpricechart_movement_1m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpricechart',
            name='fb_volume_1d',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stockpricechart',
            name='fs_volume_1d',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stockpricechart',
            name='last_volume_1d',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
