# Generated by Django 4.1.1 on 2022-11-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_stockpricechart_fb_volume_1d_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'market_index',
            },
        ),
        migrations.DeleteModel(
            name='MarketIndexPriceDaily',
        ),
        migrations.DeleteModel(
            name='StockPriceIntraday',
        ),
        migrations.RenameField(
            model_name='etfpricedaily',
            old_name='ceiling_price',
            new_name='adj_close',
        ),
        migrations.RenameField(
            model_name='etfpricedaily',
            old_name='floor_price',
            new_name='ceiling',
        ),
        migrations.RenameField(
            model_name='etfpricedaily',
            old_name='reference_price',
            new_name='floor',
        ),
        migrations.AddField(
            model_name='etfpricedaily',
            name='exchange',
            field=models.CharField(default='hose', max_length=50),
        ),
        migrations.AddField(
            model_name='etfpricedaily',
            name='reference',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='etfpricedaily',
            name='close',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='etfpricedaily',
            name='high',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='etfpricedaily',
            name='low',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='etfpricedaily',
            name='open',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='etfpricedaily',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
