# Generated by Django 4.1.1 on 2022-11-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_marketindex_delete_marketindexpricedaily_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcoIndicator',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('risk_free_rate', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('equity_risk_premium', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('corporate_tax_rate', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'marco_indicator',
            },
        ),
        migrations.CreateModel(
            name='StockFinancials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('year', models.IntegerField(db_index=True, default=0)),
                ('quarter', models.IntegerField(default=0)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('beta', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('eps', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('diluted_eps', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('bvps', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('pe', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('pb', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('peg', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('roa', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('roe', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('ros', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('cost_of_good_sold', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('gross_profit', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('operating_expenses', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('operating_income', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('interest_expense', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('ebit', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('ebitda', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('net_income', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('total_cash', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('total_liabilities', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('shareholders_equity', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('short_term_assets', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('long_term_assets', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('short_term_liabilities', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('long_term_liabilities', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'stock_financials_annually',
                'unique_together': {('symbol', 'year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='StockIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('industry_name_level_1', models.CharField(blank=True, max_length=200, null=True)),
                ('industry_code_level_1', models.CharField(blank=True, max_length=200, null=True)),
                ('industry_name_level_2', models.CharField(blank=True, max_length=200, null=True)),
                ('industry_code_level_2', models.CharField(blank=True, max_length=200, null=True)),
                ('industry_name_level_3', models.CharField(blank=True, max_length=200, null=True)),
                ('industry_code_level_3', models.CharField(blank=True, max_length=200, null=True)),
                ('industry_name_level_4', models.CharField(blank=True, max_length=200, null=True)),
                ('industry_code_level_4', models.CharField(blank=True, max_length=200, null=True)),
                ('industry_name_level_5', models.CharField(blank=True, max_length=200, null=True)),
                ('industry_code_level_5', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'stock_industry',
            },
        ),
        migrations.CreateModel(
            name='StockTA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stock_technical_analysis',
            },
        ),
        migrations.RenameModel(
            old_name='StockDividendEvent',
            new_name='StockDividend',
        ),
        migrations.DeleteModel(
            name='StockFinancialReportYearly',
        ),
        migrations.RenameField(
            model_name='stockfa',
            old_name='corporate_tax_rate',
            new_name='volume',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='cost_of_good_sold',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='datasource',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='ebit',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='ebitda',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='equity_risk_premium',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='gross_profit',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='industry_code_level_1',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='industry_code_level_2',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='industry_code_level_3',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='industry_code_level_4',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='industry_code_level_5',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='industry_name_level_1',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='industry_name_level_2',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='industry_name_level_3',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='industry_name_level_4',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='industry_name_level_5',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='interest_expense',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='long_term_assets',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='long_term_liabilities',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='market_volume',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='net_income',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='operating_expenses',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='operating_income',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='risk_free_rate',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='shareholders_equity',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='short_term_assets',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='short_term_liabilities',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='total_assets',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='total_cash',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='total_liabilities',
        ),
        migrations.RemoveField(
            model_name='stockfa',
            name='total_revenue',
        ),
        migrations.AddField(
            model_name='bank',
            name='loan_to_deposit',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='market_cap',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='non_performing_loan_ratio',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stockpricerealtime',
            name='ceiling',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stockpricerealtime',
            name='floor',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stockpricerealtime',
            name='reference',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockfa',
            name='date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterModelTable(
            name='stockdividend',
            table='stock_dividend',
        ),
        migrations.AlterModelTable(
            name='stockfa',
            table='stock_fundamental_analysis',
        ),
    ]
