# Generated by Django 4.1.1 on 2022-12-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_marcoindicator_stockfinancialsannually_stockindustry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpricerealtime',
            name='close',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockpricerealtime',
            name='high',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockpricerealtime',
            name='low',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockpricerealtime',
            name='open',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
