# Generated by Django 4.1.1 on 2022-12-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_stockfa_current_ratio_stockfa_debt_to_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpricerealtime',
            name='fb_volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='stockpricerealtime',
            name='foreign_room',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='stockpricerealtime',
            name='fs_volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='stockpricerealtime',
            name='total_trading_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stockpricerealtime',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
