# Generated by Django 4.1.1 on 2022-12-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_market_feargreedindexdaily_exchange_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIndexDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('date', models.DateField(db_index=True)),
                ('datetime', models.DateTimeField(db_index=True)),
                ('reference', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('fb_volume', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('fs_volume', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('open', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('high', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('low', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('close', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'market_index_ohlc_daily',
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
