# Generated by Django 4.1.1 on 2022-12-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_marketindexdaily'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mutualfundnavindex',
            old_name='last_nav_inception_date',
            new_name='nav_1d',
        ),
        migrations.RemoveField(
            model_name='mutualfundnavindex',
            name='last_nav_1d',
        ),
        migrations.RemoveField(
            model_name='mutualfundnavindex',
            name='last_nav_1m',
        ),
        migrations.RemoveField(
            model_name='mutualfundnavindex',
            name='last_nav_1w',
        ),
        migrations.RemoveField(
            model_name='mutualfundnavindex',
            name='last_nav_1y',
        ),
        migrations.RemoveField(
            model_name='mutualfundnavindex',
            name='last_nav_3m',
        ),
        migrations.RemoveField(
            model_name='mutualfundnavindex',
            name='last_nav_3y',
        ),
        migrations.RemoveField(
            model_name='mutualfundnavindex',
            name='last_nav_5y',
        ),
        migrations.RemoveField(
            model_name='mutualfundnavindex',
            name='last_nav_6m',
        ),
        migrations.RemoveField(
            model_name='mutualfundnavindex',
            name='last_nav_ytd',
        ),
        migrations.RemoveField(
            model_name='mutualfundnavindex',
            name='total_assets',
        ),
        migrations.AddField(
            model_name='mutualfundnavindex',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='mutualfundnavindex',
            name='nav_1m',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mutualfundnavindex',
            name='nav_1w',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mutualfundnavindex',
            name='nav_1y',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mutualfundnavindex',
            name='nav_3m',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mutualfundnavindex',
            name='nav_3y',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mutualfundnavindex',
            name='nav_5y',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mutualfundnavindex',
            name='nav_6m',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mutualfundnavindex',
            name='nav_ytd',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mutualfundnavindex',
            name='total_nav',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='mutualfundnavindex',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mutualfundnavindex',
            name='symbol',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
