# Generated by Django 4.1.1 on 2022-12-12 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_last_nav_inception_date_mutualfundnavindex_nav_1d_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockIndustry',
        ),
        migrations.RenameField(
            model_name='industry',
            old_name='code',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='feargreedindexdaily',
            name='status',
        ),
        migrations.AddField(
            model_name='stock',
            name='inception_date',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='ipo_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='ipo_shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sector_stocks', to='core.industry'),
        ),
        migrations.AddField(
            model_name='stock',
            name='sub_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_sector_stocks', to='core.industry'),
        ),
        migrations.AddField(
            model_name='stock',
            name='super_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='super_sector_stocks', to='core.industry'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.SmallIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='status',
            field=models.SmallIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='etf',
            name='status',
            field=models.SmallIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='industry',
            name='level',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='status',
            field=models.SmallIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='mutualfund',
            name='status',
            field=models.SmallIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stock',
            name='status',
            field=models.SmallIntegerField(default=1000),
        ),
    ]
