# Generated by Django 4.1.1 on 2022-12-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_stockindustry_rename_code_industry_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='industry',
            name='slug',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
