# Generated by Django 4.1.1 on 2022-12-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_industry_name_alter_industry_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='brand_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
