# Generated by Django 4.1.1 on 2022-12-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_stock_brand_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="ipo_shares",
            field=models.BigIntegerField(default=0),
        ),
    ]
