# Generated by Django 4.1.1 on 2022-12-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_etf_authorized_participants_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("symbol", models.CharField(db_index=True, max_length=50)),
                ("code", models.CharField(db_index=True, max_length=50)),
                ("name", models.CharField(max_length=500)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("exright_date", models.DateField(db_index=True, null=True)),
                ("record_date", models.DateField(db_index=True, null=True)),
                ("issue_date", models.DateField(db_index=True, null=True)),
                ("public_date", models.DateField(db_index=True, null=True)),
                (
                    "value",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "ratio",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
            ],
            options={
                "db_table": "stock_event",
                "unique_together": {("symbol", "public_date", "name")},
            },
        ),
    ]
