# Generated by Django 4.1.1 on 2022-12-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_stockevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="industry",
            name="icb_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
