# Generated by Django 4.1.1 on 2022-12-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_industry_icb_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.SmallIntegerField(default=1001),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='status',
            field=models.SmallIntegerField(default=1001),
        ),
        migrations.AlterField(
            model_name='etf',
            name='status',
            field=models.SmallIntegerField(default=1001),
        ),
        migrations.AlterField(
            model_name='industry',
            name='status',
            field=models.SmallIntegerField(default=1001),
        ),
        migrations.AlterField(
            model_name='mutualfund',
            name='status',
            field=models.SmallIntegerField(default=1001),
        ),
        migrations.AlterField(
            model_name='stock',
            name='status',
            field=models.SmallIntegerField(default=1001),
        ),
    ]
