# Generated by Django 4.1.1 on 2022-12-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_collection_status_alter_crypto_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpricerealtime',
            name='exchange',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stockpricerealtime',
            name='type',
            field=models.CharField(db_index=True, default='stock', max_length=50),
        ),
    ]
