# Generated by Django 4.1.1 on 2022-12-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_stockpricerealtime_exchange_stockpricerealtime_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="collectionindicator",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="collectionindicator",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="collectionindicator",
            name="indicator",
        ),
        migrations.AlterUniqueTogether(
            name="collectionsort",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="collectionsort",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="collectionsort",
            name="indicator",
        ),
        migrations.RemoveField(
            model_name="collection",
            name="params",
        ),
        migrations.AddField(
            model_name="collection",
            name="field_params",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="collection",
            name="filter_params",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="collection",
            name="sort_params",
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name="CollectionFilter",
        ),
        migrations.DeleteModel(
            name="CollectionIndicator",
        ),
        migrations.DeleteModel(
            name="CollectionSort",
        ),
        migrations.DeleteModel(
            name="Indicator",
        ),
    ]
