# Generated by Django 4.1.1 on 2022-12-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_collectionindicator_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StockDividend",
        ),
        migrations.AddField(
            model_name="stockfa",
            name="industry_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="stockfa",
            name="sector_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="stockfa",
            name="sub_sector_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="stockfa",
            name="super_sector_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="stockpricechart",
            name="change_percentage_1m",
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="stockpricechart",
            name="change_percentage_1w",
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="stockpricechart",
            name="change_percentage_1y",
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="stockpricechart",
            name="change_percentage_3m",
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="stockpricechart",
            name="change_percentage_3y",
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="stockpricechart",
            name="change_percentage_5y",
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="stockpricechart",
            name="change_percentage_6m",
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="stockpricechart",
            name="change_percentage_inception_date",
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="stockpricechart",
            name="change_percentage_ytd",
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="stockpricerealtime",
            name="change_percentage_1d",
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
