# Generated by Django 4.1.1 on 2023-01-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_delete_stockdividend_stockfa_industry_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("label", models.CharField(max_length=255)),
                ("group", models.CharField(db_index=True, max_length=255)),
                ("product_type", models.CharField(max_length=50)),
                ("source_model", models.CharField(max_length=100)),
                ("source_field", models.CharField(max_length=100)),
                ("data_type", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "metric",
                "unique_together": {("name", "product_type")},
            },
        ),
    ]
