# Generated by Django 4.1.1 on 2023-01-08 10:48

from django.db import migrations, models
import utils.app


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_metric"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchlistCollection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.app.item_upload_to,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                ("limit", models.IntegerField(default=12)),
                ("status", models.SmallIntegerField(default=1001)),
                ("product_type", models.CharField(default="stock", max_length=50)),
                ("field_params", models.JSONField(default=list)),
                ("filter_params", models.JSONField(default=list)),
                ("sort_params", models.JSONField(default=list)),
            ],
            options={
                "db_table": "watchlist_collection",
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="device",
            field=models.CharField(default="desktop", max_length=50),
        ),
    ]
