# Generated by Django 4.1.1 on 2023-01-10 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_watchlistcollection_collection_device"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collection",
            old_name="device",
            new_name="content_type",
        ),
    ]
