# Generated by Django 4.1.1 on 2023-01-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_cryptopricerealtime_etfpricechart_and_more"),
        ("core", "0027_rename_device_collection_content_type"),
    ]

    operations = []
