# Generated by Django 4.1.1 on 2023-01-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_merge_20230110_1041"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchindex",
            name="brand_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
