# Generated by Django 4.1.1 on 2023-01-17 17:15

from django.db import migrations, models
import django.db.models.deletion
import utils.app


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_alter_feargreedindexdaily_market_index_diff_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.app.item_upload_to,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("status", models.SmallIntegerField(default=1001)),
            ],
            options={
                "db_table": "collection_group",
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="group_collection",
                to="core.collectiongroup",
            ),
        ),
    ]
