# Generated by Django 4.1.1 on 2023-01-19 04:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_collectiongroup_collection_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryAnalytics',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('industry', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.industry')),
                ('datetime', models.DateTimeField()),
                ('market_cap', models.DecimalField(decimal_places=0, max_digits=50, null=True)),
                ('market_cap_1w', models.DecimalField(decimal_places=0, max_digits=50, null=True)),
                ('market_cap_1m', models.DecimalField(decimal_places=0, max_digits=50, null=True)),
                ('market_cap_ytd', models.DecimalField(decimal_places=0, max_digits=50, null=True)),
                ('market_cap_1y', models.DecimalField(decimal_places=0, max_digits=50, null=True)),
                ('market_cap_3y', models.DecimalField(decimal_places=0, max_digits=50, null=True)),
                ('market_cap_5y', models.DecimalField(decimal_places=0, max_digits=50, null=True)),
                ('change_percentage_1w', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('change_percentage_1m', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('change_percentage_ytd', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('change_percentage_1y', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('change_percentage_3y', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('change_percentage_5y', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('pe', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('forecasted_growth', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'industry_analytics',
                'db_table': 'industry_analytics',
            },
        ),
        migrations.RenameField(
            model_name='stockfa',
            old_name='outstanding_share',
            new_name='outstanding_shares',
        ),
        migrations.RenameField(
            model_name='stockfinancials',
            old_name='outstanding_share',
            new_name='outstanding_shares',
        ),
        migrations.AddField(
            model_name='etf',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etf',
            name='ipo_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='etf',
            name='ipo_shares',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='etf',
            name='outstanding_shares',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='outstanding_shares',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockpricedaily',
            name='market_cap',
            field=models.DecimalField(decimal_places=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='stockpricedaily',
            name='outstanding_shares',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stockpricerealtime',
            name='market_cap',
            field=models.DecimalField(decimal_places=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='stockpricerealtime',
            name='outstanding_shares',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True),
        ),
    ]
