# Generated by Django 4.1.1 on 2023-02-12 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_industryanalytics_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="industryanalytics",
            name="change_percentage_1d",
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="industryanalytics",
            name="change_percentage_3m",
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="industryanalytics",
            name="change_percentage_6m",
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="industryanalytics",
            name="icb_code",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="industryanalytics",
            name="market_cap_3m",
            field=models.DecimalField(decimal_places=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name="industryanalytics",
            name="market_cap_6m",
            field=models.DecimalField(decimal_places=0, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name="industryanalytics",
            name="datetime",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
