# Generated by Django 4.1.1 on 2023-02-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_industryanalytics_change_percentage_1d_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketIndexAnalytics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("symbol", models.CharField(max_length=50, unique=True)),
                (
                    "close",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "change_1d",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "change_1w",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "change_1m",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "change_3m",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "change_6m",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "change_1y",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "change_3y",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "change_5y",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "change_ytd",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "change_percentage_1d",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "change_percentage_1w",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "change_percentage_1m",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "change_percentage_3m",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "change_percentage_6m",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "change_percentage_1y",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "change_percentage_3y",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "change_percentage_5y",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "change_percentage_ytd",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
            ],
            options={
                "db_table": "market_index_analytics",
            },
        ),
    ]
