# Generated by Django 4.1.1 on 2023-02-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_marketindexanalytics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockevent",
            name="code",
        ),
        migrations.AlterField(
            model_name="stockevent",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockevent",
            name="name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="stockevent",
            name="ratio",
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="stockevent",
            name="value",
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
    ]
