# Generated by Django 4.1.1 on 2023-02-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_stockevent_code_alter_stockevent_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryanalytics',
            name='market_cap_1d',
            field=models.DecimalField(decimal_places=0, max_digits=50, null=True),
        ),
    ]
