# Generated by Django 4.1.1 on 2023-02-27 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_industryanalytics_market_cap_1d'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketindexanalytics',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
