# Generated by Django 4.1.1 on 2023-03-02 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_marketindexanalytics_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='NewsPost',
        ),
        migrations.DeleteModel(
            name='Sentiment',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
