# Generated by Django 4.1.1 on 2023-03-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_delete_category_delete_newspost_delete_sentiment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchindex',
            name='photo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
