# Generated by Django 4.1.1 on 2023-03-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_searchindex_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpricechart',
            name='fb_volume_1d',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockpricechart',
            name='fs_volume_1d',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockpricechart',
            name='last_price_1d',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockpricechart',
            name='last_volume_1d',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockpricechart',
            name='reference',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
