# Generated by Django 4.1.1 on 2023-03-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_stockpricechart_fb_volume_1d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockfa',
            name='company_type',
            field=models.CharField(blank=True, default='COMPANY', max_length=50, null=True),
        ),
    ]
