# Generated by Django 4.1.1 on 2023-03-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_stockpricechart_fb_volume_1d_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPriceAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(db_index=True, max_length=50, unique=True)),
                ('datetime', models.DateTimeField()),
                ('reference', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('price_1d', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('volume_1d', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('fb_volume_1d', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('fs_volume_1d', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('change_percentage_1d', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('price_1w', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('price_1m', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('price_3m', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('price_6m', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('price_1y', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('price_3y', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('price_5y', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('price_ytd', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('price_inception_date', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('change_percentage_1w', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('change_percentage_1m', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('change_percentage_3m', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('change_percentage_6m', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('change_percentage_1y', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('change_percentage_3y', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('change_percentage_5y', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('change_percentage_ytd', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('change_percentage_inception_date', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('volume_1w', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('volume_1m', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('volume_3m', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('volume_6m', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('volume_1y', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('volume_3y', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('volume_5y', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'stock_price_analytics',
                'db_table': 'stock_price_analytics',
            },
        ),
    ]
