# Generated by Django 4.1.1 on 2023-03-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_stockpriceanalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfundpricechart',
            name='nav_1m',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mutualfundpricechart',
            name='nav_1w',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mutualfundpricechart',
            name='nav_1y',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mutualfundpricechart',
            name='nav_3m',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mutualfundpricechart',
            name='nav_3y',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mutualfundpricechart',
            name='nav_5y',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mutualfundpricechart',
            name='nav_6m',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='mutualfundpricechart',
            name='nav_ytd',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
