# Generated by Django 4.1.1 on 2023-03-16 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_stockfa_company_type'),
        ('core', '0043_mutualfundpricechart_nav_1m_and_more'),
    ]

    operations = [
    ]
