# Generated by Django 4.1.1 on 2023-03-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_merge_20230316_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpriceanalytics',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
