# Generated by Django 4.1.1 on 2023-03-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_stockpriceanalytics_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('status', models.SmallIntegerField(default=1001)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'market_calendar',
            },
        ),
    ]
