# Generated by Django 4.1.1 on 2023-03-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_marketcalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketindexanalytics',
            name='close_1d',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='marketindexanalytics',
            name='close_1m',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='marketindexanalytics',
            name='close_1w',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='marketindexanalytics',
            name='close_1y',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='marketindexanalytics',
            name='close_3m',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='marketindexanalytics',
            name='close_3y',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='marketindexanalytics',
            name='close_5y',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='marketindexanalytics',
            name='close_6m',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='marketindexanalytics',
            name='close_ytd',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
