# Generated by Django 4.1.1 on 2023-04-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_stockpricechart_change_percentage_1m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='market_cap_rank',
            field=models.IntegerField(db_index=True, default=99999),
        ),
    ]
