# Generated by Django 4.1.1 on 2023-04-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_alter_crypto_market_cap_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockevent",
            name="dividend_type",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("stock", "Stock"),
                    ("hybrid", "Hybrid"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
