# Generated by Django 4.1.1 on 2023-04-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_stockevent_dividend_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpricerealtime',
            name='ordering',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
