# Generated by Django 4.1.1 on 2023-06-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_stockpricerealtime_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockevent",
            name="event_type",
            field=models.CharField(
                choices=[("dividend", "Dividend"), ("issue", "Issue")],
                default="dividend",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="stockevent",
            name="dividend_type",
            field=models.CharField(
                choices=[("cash", "Cash"), ("stock", "Stock")],
                default="cash",
                max_length=50,
            ),
        ),
    ]
