# Generated by Django 4.1.1 on 2023-07-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_stockevent_event_type_alter_stockevent_dividend_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockevent',
            name='dividend_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('stock', 'Stock')], default='cash', max_length=50, null=True),
        ),
    ]
