# Generated by Django 4.1.1 on 2023-08-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_stockevent_dividend_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfundnavindex',
            name='annualized_return_n_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mutualfundnavindex',
            name='annualized_return_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
