# Generated by Django 4.1.1 on 2023-08-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_mutualfundnavindex_annualized_return_n_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundPriceAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(db_index=True, max_length=50, unique=True)),
                ('date', models.DateField(null=True)),
                ('datetime', models.DateTimeField()),
                ('nav', models.DecimalField(decimal_places=2, max_digits=20)),
                ('annualized_return_percentage', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('annualized_return_n_year', models.IntegerField(null=True)),
                ('maximum_drawdown_percentage', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('nav_1w', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('nav_1m', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('nav_3m', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('nav_6m', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('nav_1y', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('nav_3y', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('nav_5y', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('nav_ytd', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('nav_inception_date', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('change_percentage_1w', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('change_percentage_1m', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('change_percentage_3m', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('change_percentage_6m', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('change_percentage_1y', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('change_percentage_3y', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('change_percentage_5y', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('change_percentage_ytd', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('change_percentage_inception_date', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'fund_nav_analytics',
                'db_table': 'fund_nav_analytics',
            },
        ),
        migrations.RemoveField(
            model_name='mutualfundnavindex',
            name='annualized_return_n_year',
        ),
        migrations.RemoveField(
            model_name='mutualfundnavindex',
            name='annualized_return_percentage',
        ),
    ]
