# Generated by Django 4.1.1 on 2023-08-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_rename_fundpriceanalytics_fundnavanalytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('public_date', models.DateField(db_index=True, null=True)),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('record_date', models.DateField(db_index=True, null=True)),
                ('exright_date', models.DateField(db_index=True, null=True)),
                ('issue_date', models.DateField(db_index=True, null=True)),
                ('value', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('ratio', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('dividend_type', models.CharField(choices=[('cash', 'Cash'), ('stock', 'Stock')], default='cash', max_length=50, null=True)),
                ('event_type', models.CharField(choices=[('dividend', 'Dividend'), ('issue', 'Issue')], default='dividend', max_length=50)),
            ],
            options={
                'db_table': 'stock_event_log',
            },
        ),
    ]
