# Generated by Django 4.1.1 on 2023-11-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_stockeventlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIndexValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('exchange', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('open', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('change_percentage_1d', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_volume', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('ordering', models.IntegerField(db_index=True, default=0)),
                ('status', models.SmallIntegerField(default=1001)),
            ],
            options={
                'db_table': 'market_index_value',
                'unique_together': {('symbol',)},
            },
        ),
    ]
