# Generated by Django 4.1.1 on 2023-12-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_marketindexvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchindex',
            name='type',
            field=models.CharField(db_index=True, default='STOCK', max_length=50),
        ),
        migrations.AlterField(
            model_name='stockpricerealtime',
            name='type',
            field=models.CharField(db_index=True, default='STOCK', max_length=50),
        ),
    ]
