# Generated by Django 4.1.1 on 2024-04-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_searchindex_type_alter_stockpricerealtime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryanalytics',
            name='id',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
