# Generated by Django 4.1.1 on 2024-04-11 07:10

from django.db import migrations, models
import uuid


def forwards_func(apps, schema_editor):
    Model = apps.get_model("core", "industryanalytics")
    for id, obj in enumerate(Model.objects.all()):
        obj.id = uuid.uuid4()
        obj.save()


def reverse_func(apps, schema_editor):
    Model = apps.get_model("core", "industryanalytics")
    for obj in Model.objects.all():
        obj.id = None
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_industryanalytics_id"),
    ]

    operations = [
        migrations.RunPython(code=forwards_func, reverse_code=reverse_func),
        migrations.AlterField(
            model_name="industryanalytics",
            name="id",
            field=models.UUIDField(editable=False, null=False),
        ),
    ]
