# Generated by Django 4.1.1 on 2024-04-11 09:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_fix_industryanalytics_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryanalytics',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='industryanalytics',
            name='industry',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, null=False),
        ),
    ]
