# Generated by Django 4.1.1 on 2024-04-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_industryanalytics_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industryanalytics',
            old_name='industry',
            new_name='industry_id',
        ),
    ]
