# Generated by Django 4.1.1 on 2024-04-11 09:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_rename_industry_industryanalytics_industry_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="industryanalytics",
            name="industry_id",
            field=models.IntegerField(db_index=True, primary_key=False, unique=True),
        ),
        migrations.AlterField(
            model_name="industryanalytics",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
