# Generated by Django 4.1.1 on 2024-09-26 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_industryanalytics_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ETFIIndexDaily',
        ),
        migrations.DeleteModel(
            name='ETFNavDaily',
        ),
        migrations.DeleteModel(
            name='ETFPriceDaily',
        ),
        migrations.DeleteModel(
            name='MarketIndexDaily',
        ),
        migrations.DeleteModel(
            name='StockPriceDaily',
        ),
    ]
