# Generated by Django 4.1.1 on 2024-10-02 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_remove_etfpricechart_fb_volume_1d_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketindexanalytics',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
