# Generated by Django 4.1.1 on 2024-10-02 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_marketindexanalytics_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etf',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='etfpricechart',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='feargreedindexdaily',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ('-created',), 'verbose_name_plural': 'industries'},
        ),
        migrations.AlterModelOptions(
            name='industryanalytics',
            options={'ordering': ('-created',), 'verbose_name_plural': 'industry_analytics'},
        ),
        migrations.AlterModelOptions(
            name='marketcalendar',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='marketindex',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='marketindexanalytics',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='marketindexvalue',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='stockfinancials',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='stockpriceanalytics',
            options={'ordering': ('-created',), 'verbose_name_plural': 'stock_price_analytics'},
        ),
        migrations.AlterModelOptions(
            name='stockpricechart',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='stockpricerealtime',
            options={'ordering': ('-created',)},
        ),
    ]
