# Generated by Django 4.1.1 on 2024-10-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_alter_etf_options_alter_etfpricechart_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etfpricechart',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='etfpricechart',
            name='total_trading_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
