# Generated by Django 4.1.1 on 2024-12-13 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_etfpriceanalytics_etfpricerealtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketindex',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.AlterField(
            model_name='marketindex',
            name='symbol',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='MarketIndexStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('market_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marketindex')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stock')),
            ],
            options={
                'db_table': 'market_index_stock',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='marketindex',
            name='stocks',
            field=models.ManyToManyField(through='core.MarketIndexStock', to='core.stock'),
        ),
    ]
