# Generated by Django 4.1.1 on 2024-12-17 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_remove_marketindex_id_remove_stock_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marketindexstock',
            unique_together={('stock', 'market_index')},
        ),
    ]
