# Generated by Django 4.1.1 on 2025-03-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_fundnavanalytics_fund_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutualfund',
            name='id',
        ),
        migrations.AlterField(
            model_name='mutualfund',
            name='symbol',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
