# Generated by Django 4.1.1 on 2025-03-07 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_remove_mutualfund_id_alter_mutualfund_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutualfundnavindex',
            name='fund',
        ),
    ]
