# Generated by Django 4.1.1 on 2025-03-07 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_remove_mutualfundnavindex_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfundnavindex',
            name='fund',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.mutualfund'),
        ),
    ]
