# Generated by Django 4.1.1 on 2025-03-07 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_mutualfundnavindex_fund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundnavanalytics',
            name='fund',
        ),
        migrations.RemoveField(
            model_name='mutualfundpricechart',
            name='fund',
        ),
    ]
