# Generated by Django 4.1.1 on 2025-03-07 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_remove_fundnavanalytics_fund_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundnavanalytics',
            name='fund',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.mutualfund'),
        ),
        migrations.AddField(
            model_name='mutualfundpricechart',
            name='fund',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.mutualfund'),
        ),
    ]
