# Generated by Django 4.1.1 on 2025-03-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_mutualfund_is_on_stag'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIndexDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('date', models.DateField()),
                ('datetime', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('high', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('low', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('close', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('total_volume', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
            options={
                'db_table': 'market_index_daily',
                'ordering': ('symbol',),
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
