# Generated by Django 4.1.1 on 2025-04-01 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_marketindexdaily'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockFinancials',
        ),
    ]
