# Generated by Django 4.1.1 on 2025-04-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_delete_stockfinancials'),
    ]

    operations = [
        migrations.AddField(
            model_name='etfpricechart',
            name='movement_all',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='etfpricechart',
            name='volume_all',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
